title: Juncture
tagline: Examples
banner: /images/hero-juncture.png
favicon: /images/favicon.svg
logo: /images/logo-juncture.svg

# When using a custom domain these fields must be updated to match
# the account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: Home
  icon: fas fa-home
  action: load-page
  path: /
- label: Documentation
  icon: fas fa-file-alt
  action: load-page
  path: /docs
- label: Tags quick reference
  icon: fas fa-code
  action: load-page
  path: /docs/tags
- label: Contact Us
  icon: fas fa-envelope
  action: contact-us

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form
# A valid toEmail address is required. Other fields are optional
contactForm:
  from: JSTOR Labs <labs@ithaka.org>
  to:
  #- labs@ithakaorg.onmicrosoft.com
  - Ron Snyder <Ron.Snyder@ithaka.org>
  subject: Juncture Contact Form
